//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoppingStoreDbEntities : DbContext
    {
        public ShoppingStoreDbEntities()
            : base("name=ShoppingStoreDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<SiteSetting> SiteSetting { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_Comment> Tbl_Comment { get; set; }
        public virtual DbSet<Tbl_Guaranty> Tbl_Guaranty { get; set; }
        public virtual DbSet<Tbl_Menu> Tbl_Menu { get; set; }
        public virtual DbSet<Tbl_Order> Tbl_Order { get; set; }
        public virtual DbSet<Tbl_Pictures> Tbl_Pictures { get; set; }
        public virtual DbSet<Tbl_Post> Tbl_Post { get; set; }
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<Tbl_ProductImage> Tbl_ProductImage { get; set; }
        public virtual DbSet<Tbl_Prouducts_Categories> Tbl_Prouducts_Categories { get; set; }
        public virtual DbSet<Tbl_SliderImage> Tbl_SliderImage { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
    }
}
