//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebStoreDbEntities5 : DbContext
    {
        public WebStoreDbEntities5()
            : base("name=WebStoreDbEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<SiteSetting> SiteSetting { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_Comment> Tbl_Comment { get; set; }
        public virtual DbSet<Tbl_ContactUs> Tbl_ContactUs { get; set; }
        public virtual DbSet<Tbl_Employee> Tbl_Employee { get; set; }
        public virtual DbSet<Tbl_Guaranty> Tbl_Guaranty { get; set; }
        public virtual DbSet<Tbl_InstantOffer> Tbl_InstantOffer { get; set; }
        public virtual DbSet<Tbl_MainCategory_Image> Tbl_MainCategory_Image { get; set; }
        public virtual DbSet<Tbl_MessageSituation_ContactUs> Tbl_MessageSituation_ContactUs { get; set; }
        public virtual DbSet<Tbl_Order> Tbl_Order { get; set; }
        public virtual DbSet<Tbl_Pictures> Tbl_Pictures { get; set; }
        public virtual DbSet<Tbl_Post> Tbl_Post { get; set; }
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<Tbl_ProductImage> Tbl_ProductImage { get; set; }
        public virtual DbSet<Tbl_Prouducts_Categories> Tbl_Prouducts_Categories { get; set; }
        public virtual DbSet<Tbl_SliderImage> Tbl_SliderImage { get; set; }
        public virtual DbSet<Tbl_SubTitle_image> Tbl_SubTitle_image { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_OurWebsites> Tbl_OurWebsites { get; set; }
        public virtual DbSet<Tbl_UserTest> Tbl_UserTest { get; set; }
    }
}
