//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSetting
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string SiteDescription { get; set; }
        public string MetaTags { get; set; }
        public Nullable<bool> DisplayCommentAfterConfirm { get; set; }
        public Nullable<bool> DisableComment { get; set; }
        public Nullable<int> MaxUploadSize { get; set; }
        public string ValidFormat { get; set; }
        public Nullable<int> DisplayProductCount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> ValueAddedPercentage { get; set; }
    }
}
