//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Comment()
        {
            this.Tbl_Comment1 = new HashSet<Tbl_Comment>();
        }
    
        public int ID { get; set; }
        public int ProductID_FK { get; set; }
        public int CommentID_FK { get; set; }
        public string UserFullName { get; set; }
        public string UserEmail { get; set; }
        public string CommentContent { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public bool Comment_Confirm { get; set; }
        public bool Comment_IsRead { get; set; }
        public int Comment_Like { get; set; }
        public int Comment_Dislike { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Comment> Tbl_Comment1 { get; set; }
        public virtual Tbl_Comment Tbl_Comment2 { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
