//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SliderImage
    {
        public int ID { get; set; }
        public string ImageName { get; set; }
        public string ImageCaption { get; set; }
        public string ImageText { get; set; }
        public string Link { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
