//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Product()
        {
            this.ShoppingCart = new HashSet<ShoppingCart>();
            this.Tbl_Comment = new HashSet<Tbl_Comment>();
            this.Tbl_Order = new HashSet<Tbl_Order>();
            this.Tbl_Prouducts_Categories = new HashSet<Tbl_Prouducts_Categories>();
            this.Tbl_ProductImage = new HashSet<Tbl_ProductImage>();
        }
    
        public int ProductID { get; set; }
        public string ProductTitle { get; set; }
        public string ProductEnglishTitle { get; set; }
        public decimal Price { get; set; }
        public int AvailaibleCout { get; set; }
        public string Description { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public decimal Product_Off { get; set; }
        public double Visit { get; set; }
        public double Product_Like { get; set; }
        public double Product_Dislike { get; set; }
        public int UserRegisterID_FK { get; set; }
        public int GurantyID_FK { get; set; }
        public long Sales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Comment> Tbl_Comment { get; set; }
        public virtual Tbl_Guaranty Tbl_Guaranty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Order> Tbl_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Prouducts_Categories> Tbl_Prouducts_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ProductImage> Tbl_ProductImage { get; set; }
    }
}
